# 운영 서버
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      database: 0

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  file:
    path: /app/logs
  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 1GB
      max-history: 14
  level:
    org.hibernate.SQL: warn
    root: info
