# 공통 설정
cloud:
  aws:
    s3:
      region: ap-northeast-2
      presigned-url-expire-seconds: 600
      max-file-size-bytes: 5242880

cors:
  allowed-origins:
    - http://localhost:5173

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: framework

spring:
  application:
    name: hufsdev

  data:
    web:
      pageable:
        max-page-size: 100

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  session:
    store-type: redis
    redis:
      namespace: "{hufsdev:session}"

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

piston:
  api:
    timeout-seconds: 15
