# 공통 설정
spring:
  application:
    name: hufsdev

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  session:
    store-type: redis
    redis:
      namespace: hufsdev:session

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
