# 운영 서버
cors:
  allowed-origins:
    - https://hufs.dev

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 3s
      ttl:
        auth-code-minutes: 5
        session-minutes: 30
        limit-seconds: 60
      ssl:
        enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    domain: "@hufs.ac.kr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true

    readinessstate:
      enabled: true

    mail:
      enabled: false

logging:
  file:
    path: /app/logs
  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 1GB
      max-history: 14
  level:
    org.hibernate.SQL: warn
    root: info
