# 공통 설정
cors:
  allowed-origins:
    - http://localhost:5173

spring:
  application:
    name: REDACTED_DB_PASSWORD

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    web:
      pageable:
        max-page-size: 100

  session:
    store-type: redis
    redis:
      namespace: REDACTED_DB_PASSWORD:session

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
